### ISSUE TITLE
Allow forced style of markdown-style links.

### ISSUE THREAD

**Issue by jacobb** [Feel-ix-343/markdown-oxide#104]
In Obsidian, if you choose to use Markdown links, you're still able to use `[[` to start triggering an autocomplete. Once finished, however, it expands to markdown style. I'd love to have this supported with oxide

**Comment by Feel-ix-343** [comment]
Hey!

This is straightforward enough. 

- [ ] Add config option
- [ ] Implement in completions

**Comment by RyanGreenup** [comment]
Having just looked at this code, I would actually vote against.

I myself avoid wikilinks in favour of more portable markdown links.

However, this can already be solved with with a snippet:

```
# ~/.config/nvim/snippets/markdown.snippets

snippet [[ "Wikilink to MD Link" A
	[$2]($1) $0
```

Or even straight in vim:

```vim
" ~/.config/nvim/init.vim
autocmd FileType markdown inoremap [[ [](
```

Whereas if we add it to the source, we'd either have to:

1. Modify the [completion_text_edit](https://github.com/Feel-ix-343/markdown-oxide/blob/main/src/completion/link_completer.rs#L355) method to return a different format
2. Possibly (not sure) have [this line](https://github.com/Feel-ix-343/markdown-oxide/blob/main/src/completion/mod.rs#L68) return `Option::None` if `settings.wikilink_override` is `True`

Either way, it's another config item and more code addressing an issue that vim already handles quite well.


@jacobb Is there a reason this can't be handled with snippets or `imap?

**Comment by Feel-ix-343** [comment]
Too add, I remember @sQVe uses snippets for his markdown links. 

I think @RyanGreenup brings up a good related point too: we are a pkm not a text editor; this means that things that can be handled by the text editor should. 

As always, thanks for the discussion!

**Comment by RyanGreenup** [comment]
Could also be good to have an FAQ / Design Decisions in #84
