### ISSUE TITLE
Contextual completions

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#107]
Interpret the context around a wikilink using vector database when giving link completions. This could be: give completions on an empty input by finding entities *related* to the context and another feature, use a relatedness metric in the completion fuzzy finding ranking algorithm.

**Comment by RyanGreenup** [comment]
Somewhat related is: 

- llm.nvim
- llm-ls

We could find related entries by using something like tantivy or even Bert (There is a crate). 

But both require indexing which is going to require user intervention (and in the case of Bert weights + torch).

Would this be outside scope for an LSP though?
Generally speaking, it's not too hard to write a script that pulls some context from the clipboard and then suggests links, one can just pipe that to fzf / dmenu. 

If time permits, I'll write up a minimum working example in Python.

**Comment by Feel-ix-343** [comment]
Hey that sounds great!

> Would this be outside scope for an LSP though?

Well I would say that this is not an LSP, but a true PKM that uses the LSP to make things happen in your favorite text editor. Editor specific plugins are also in scope as long as they are implemented across editors. 

Therefore, if an LLM would aid in the PKM experience, then it is in scope

**Comment by Feel-ix-343** [comment]
This is still planned, but I am not thinking about it much at the moment -- semantic search is closer to where I am at.
