### ISSUE TITLE
Slow exit(:q) time in Neovim

### ISSUE THREAD

**Issue by arthurbdev** [Feel-ix-343/markdown-oxide#110]
Hey, thank you for your work.

I noticed there is a noticeable(2-3s) delay when exiting(`:q`) neovim from a markdown file with your lsp launched. However, if i switch to a different file, lua for example, there is no delay

Installed  through `:Mason`  

Neovim version
```sh
❯ nvim --version
NVIM v0.10.0-dev-3087+gbb032d952b
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
```

Let me know if you need more details

**Comment by Feel-ix-343** [comment]
Hey thanks for the contribution!

I don't have this issue as my neovim closes instantly. 

Would you mind disabling markdown oxide `:LspStop` then quitting and seeing if there is still a delay?

**Comment by arthurbdev** [comment]
After some debugging I realized it was a configuration bug on my part:
```lua
vim.api.nvim_create_autocmd("LspDetach", {
			group = vim.api.nvim_create_augroup("kickstart-lsp-detach", { clear = true }),
			callback = function(event)
				vim.lsp.buf.clear_references()
				vim.lsp.codelens.clear()
				vim.lsp.inlay_hint.enable(false)

				-- this line after doing :LspStop outputs an error 
                               vim.api.nvim_clear_autocmds({ group = "kickstart-lsp-highlight", buffer = event.buf })
				
                               vim.api.nvim_clear_autocmds({ group = "custom-lsp-codelens", buffer = event.buf })
			end,
		})
```

Sorry for disturbance and thank you for a great LSP!

**Comment by Feel-ix-343** [comment]
Thank you! Feel free to open issues for anything else!
