### ISSUE TITLE
Unindented block completion completes the full file path

### ISSUE THREAD

**Issue by realhackcraft** [Feel-ix-343/markdown-oxide#119]
The unindented block completion completes the full file path instead of a shortened, wikilink style filename.

# What I Expect:

`[[05 fifth note^abcde|Sear]]`

# What Happened

`[[01 first folder/05 fifth note^abcde|Sear]]`

**Comment by Feel-ix-343** [comment]
Hey! Thanks for reporting this.


It should be an easy fix!

**Comment by Feel-ix-343** [comment]
This will likely be a part of v1, given a much better completion API.

**Comment by Feel-ix-343** [comment]
To be honest, this can be covered by #80
