### ISSUE TITLE
Add optional image previewing through image.nvim using lsp hover

### ISSUE THREAD

**Issue by AlejandroGomezFrieiro** [Feel-ix-343/markdown-oxide#121]
Using lsp hover it might be possible to preview images using image.nvim

**Comment by Feel-ix-343** [comment]
Oh this is neat. Yea for sure we can look into this. Thank you!

**Comment by Feel-ix-343** [comment]
Unfortunately I don't think this is in scope for the language server. Possibly with a dedicated plugin in the future. For now, I am going to close this.
