### ISSUE TITLE
How do you achieve real-time preview of markdown on nvim?

### ISSUE THREAD

**Issue by Xuyaoyan** [Feel-ix-343/markdown-oxide#139]

**Comment by Feel-ix-343** [comment]
Hey!

Though I don't think this is in the scope of the project, there are some neovim plugins for this. https://github.com/iamcco/markdown-preview.nvim is a popular one. 

I typically just use Obsidian though

**Comment by Xuyaoyan** [comment]
thanks, i thought this was a built-in function of this plugin

**Comment by Feel-ix-343** [comment]
No problem! Comment again for anything else!

**Comment by Xuyaoyan** [comment]
Thank you for your positive response to me. What I want to express is actually how you can achieve real-time rendering like typora. I have also used markdown-preview, but it can only be opened in the browser. obsidian.nvim seems to only support some, like I cannot directly render the callout, bold and italic formats in your gif. thanks again

**Comment by Feel-ix-343** [comment]
Oh okay, so you want to see the rendered view in real time? 

There are a few new cool plugins that support this: 
- https://github.com/OXY2DEV/markview.nvim: Very experimental but best looking
- https://github.com/MeanderingProgrammer/markdown.nvim: Works well and I think I used it in some of the gifs
- https://github.com/lukas-reineke/headlines.nvim: This one looks very neat, but was a bit too overbearing for me. 

I hope this helps!

**Comment by Feel-ix-343** [comment]
Perhaps we should add this information to the README/Wiki (#84)

**Comment by Xuyaoyan** [comment]
oh, that's nice! Maybe someone like me are using nvim and your plugin to edit markdown for the first time! Thanks a lot!
