### ISSUE TITLE
Build failure on stable rust release channel

### ISSUE THREAD

**Issue by photosheep** [Feel-ix-343/markdown-oxide#141]
I've been maintaining this in a personal OBS repo and have run into issues building since 0.0.19. I'm not sure if this is something that can be fixed trivially, since async_closure is an unstable feature.

Relevant failure.
```
[   78s] error[E0554]: `#![feature]` may not be used on the stable release channel
```

Full build log -- [build.log](https://github.com/user-attachments/files/16111191/build.log)

**Comment by Feel-ix-343** [comment]
Hey!

The answer is to use rust nightly.

Are you able to do this, if not, I can come up with something else - a different branch or version without the async closure.

**Comment by Feel-ix-343** [comment]
let me know!

**Comment by Feel-ix-343** [comment]
Perfect!
