### ISSUE TITLE
Feature: table formating

### ISSUE THREAD

**Issue by godalming123** [Feel-ix-343/markdown-oxide#142]
I think that being able to format a markdown table would be very nice.

So this:
```
| Column A | Column B       |
| -   - |   - |
| a      | A                                                      |
| b             | B |
| c  |      C |
```
Would become this:
```
| Column A | Column B  |
| -------- | --------- |
| a        | A         |
| b        | B         |
| c        | C         |
```

**Comment by godalming123** [comment]
Yeah, I've been using the dprint formater to do this with the following set of setup instructions:

### How to install the [dprint](https://dprint.dev/) formatter for markdown

_Note:_ This setup needs my helix dotfiles to configure helix to use the dprint command to format files.

1. Install dprint:
   ```sh
   curl -fsSL https://dprint.dev/install.sh | sh
   ```
2. Add an alias for dprint by adding the following line to `~/.config/fish/config.fish`:
   ```fish
   alias dprint "~/.dprint/bin/dprint --config ~/.dprint/dprint.json"
   ```
3. Setup dprint config
   ```sh
   dprint init -c ~/.dprint/dprint.json
   ```

Although the language server protocol defianately also has this feature, and it would noticably simplify my setup to not configure dprint.

**Comment by Feel-ix-343** [comment]
Neat, so we could just use dprint, no?

**Comment by godalming123** [comment]
> Neat, so we could just use dprint, no?

I don't know exactly what you mean, but this theoretical implementation would make it possible to just:
1. Run `cargo install DPRINT-INSTALL-COMMAND`
2. Run `dprint`, without any other configuration

This implementation also shouldn't need any external libraries if thats what your asking.

**Comment by EphemeralDev** [comment]
I use deno to format markdown which i believe uses dprint under the hood. Might be able to use it as a reference.

**Comment by Feel-ix-343** [comment]
I think this might be done better on the client side. Closing for now.
