### ISSUE TITLE
References are case sensitive

### ISSUE THREAD

**Issue by Azakidev** [Feel-ix-343/markdown-oxide#144]
In Obsidian, references, or at least wikilinks, are case insensitive

For example, a file called Example.md (very original, I know) is talked about in another file, referencing as [[example]] in the middle of a sentence.

This behavior is not the same in markdown-oxide, and I consider that to be a bug as I extensively use it for a wiki on one of my projects, is there any way to make the references case insensitive?

(I messed up and shift entered by accident, therefore the edit)

**Comment by Feel-ix-343** [comment]
Hey!

Thank you for the write up and trying moxide!

This is quite easy to implement. (In fact I thought I had programmed it already!)

**Comment by Feel-ix-343** [comment]
Hey let me know what you think

**Comment by Feel-ix-343** [comment]
I will make another release once I have transclusion with inlay hints figured out
