### ISSUE TITLE
Recognize markdown reference link in form of link text with spaces

### ISSUE THREAD

**Issue by clobrano** [Feel-ix-343/markdown-oxide#145]
Disclaimer: I am not entirely sure this is up to markdown-oxide, so excuse me in advance if not.

I noticed that markdown reference links in form of link text (an example below) are recognized only if there are no spaces, however I think spaces should be supported (most markdown renderers do support them, for example on GitLab)

example
```
1. [reference-link-without-spaces]
2. [reference link with spaces]

then, somewhere in the page you also have
[reference-link-without-spaces]: https://somewhere.com
[reference link with spaces]: https://somewhereelse.com
```

The first link is recognized, and I can use for example `nmap('K', vim.lsp.buf.hover, 'Hover Documentation')` to show the floating window with information. The second link is not recognized instead.

**Comment by Feel-ix-343** [comment]
Hey! Thank you for reporting

**Comment by Feel-ix-343** [comment]
I am making a new parser for v1 that is much more align to typical markdown. This feature will be part of that!

**Comment by Feel-ix-343** [comment]
as this is planned v1 => not a current issue; closing

**Comment by Feel-ix-343** [comment]
if I forget to implement in v1, please reopen (if I don't!)
