### ISSUE TITLE
Neovim capabilities.workspace.didChangeWatchedFiles recommendation is doubtful

### ISSUE THREAD

**Issue by powerman** [Feel-ix-343/markdown-oxide#152]
In https://oxide.md/v0/Guides/Getting+started+with+Markdown+Oxide+Version+0#Neovim you insist on enabling capabilities.workspace.didChangeWatchedFiles.dynamicRegistration but it is disabled on some OSes for a reason (check issues mentioned on this line): https://github.com/neovim/neovim/blob/2a24d0a4357d24d6edbd454ab2465abf460467db/runtime/lua/vim/lsp/protocol.lua#L536

Maybe it makes sense to remove this recommendation and just wait until Neovim will resolve these issues and re-enable this capability?

**Comment by Feel-ix-343** [comment]
Hey! Thank you for the contribution!

This is an interesting one. The file watcher is currently required for a few features I use frequently, so for me, I see a few options. 

- Roll our own file watcher
- Inform the users of the features enabled by the file watcher
- (current) Suggest that everybody use this one, even with with its limitations

I have picked the latter and it has works fine for me. note that it is _very slow_, but other than that, it works. 

Considering these options now, I think 2 is certainly the best.

TODO:
- [ ] Modify the docs

**Comment by powerman** [comment]
Maybe one more option is to ensure this option will be enabled just for this one LSP, e.g. change docs to something like this:

```
require('lspconfig').markdown_oxide.setup {
    capabilities = vim.tbl_deep_extend(
        'force',
        capabilities,
        {
            workspace = {
                didChangeWatchedFiles = {
                    dynamicRegistration = true,
                },
            },
        }
    ),
}
```
Because in a way it's shown in the doc now it looks like very usual lspconfig setup, but in that usual setup we prepare `capabilities` once and then use them for all LSP, so there is a high chance users will copy&paste it from the doc and occasionally apply to all their LSP.

**Comment by Feel-ix-343** [comment]
Yes this is best.

Are you at all interested in making this change?

The docs are in the docs folder

**Comment by powerman** [comment]
Not really. English is not my native language and I usually write docs in a different style, so I'll leave this for you. :smile:

**Comment by Feel-ix-343** [comment]
All good!
