### ISSUE TITLE
LSP does not attach when workspace contains too many files

### ISSUE THREAD

**Issue by pwntester** [Feel-ix-343/markdown-oxide#154]
Hey, thanks for the project, looking forward to give it a go to use Neovim with my Obsidian vault.

I set it up with Mason and Lspconfig and seems to be attaching for non-obsidian markdown files. However, when I open an obsidian markdown file, it wont attach to it. According to LSP log is not even trying to!

I tried removing some files/folders from my obsidian vault until I removed `Journal/` and the LSP finally got attached. There is nothing special in this directory, just 550 markdown files with names in ISO format dates (eg: 2024-01-19.md)

Thanks!

**Comment by Feel-ix-343** [comment]
Ah okay right. Thanks for reporting.

Do you or have you used logseq by any chance?

**Comment by pwntester** [comment]
Yep, I moved from Logseq to Obsidian time ago.

**Comment by pwntester** [comment]
Just for reference, I have 2071 markdown files total in my Obsidian vault

**Comment by Feel-ix-343** [comment]
This is an odd one, but I hope I can help. 

I have 4400 files and I use this every day, so I don't think that is the issue. 

Could you post your LspInfo for when the server does attach?

**Comment by pwntester** [comment]
Hmmm, interesting, in that case, there may be a file in my Journal directory that breaks moxide parsing maybe. Is there anyway of dumping debug info?

LspInfo with Journal:

```md
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/pwntester/.local/state/nvim/lsp.log
 Detected filetype:   markdown
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: markdown
 
 Config: markdown_oxide
 	filetypes:         markdown
 	root directory:    /Users/pwntester/obsidian
 	cmd:               /Users/pwntester/.local/share/nvim/mason/bin/markdown-oxide
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: jsonls, yamlls, gopls, tsserver, lua_ls, pyright, dockerls, codeqlls, markdown_oxide, bashls
```

LspInfo without Journal:

```md
 Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /Users/pwntester/.local/state/nvim/lsp.log
 Detected filetype:   markdown
 
 1 client(s) attached to this buffer: 
 
 Client: markdown_oxide (id: 1, bufnr: [1])
 	filetypes:       markdown
 	autostart:       true
 	root directory:  /Users/pwntester/obsidian
 	cmd:             /Users/pwntester/.local/share/nvim/mason/bin/markdown-oxide
 
 Configured servers list: jsonls, bashls, yamlls, gopls, tsserver, lua_ls, pyright, codeqlls, markdown_oxide, dockerls
```

**Comment by Feel-ix-343** [comment]
Thank you!

Could you post logs from `/Users/pwntester/.local/state/nvim/lsp.log`? Perhaps enable debug too by a `vim.lsp.set_log_level("debug")`

**Comment by pwntester** [comment]
I think I found the issue. There are some entries which are really big for a text file:

```
❯ du -ah . | sort -rh | head -n 17
110M    .
 22M    ./2023-09-19.md
 20M    ./2023-09-20.md
 15M    ./2023-09-11.md
 14M    ./2023-09-21.md
6.7M    ./2023-10-02.md
5.9M    ./2023-10-20.md
4.9M    ./2023-09-26.md
4.7M    ./2023-09-05.md
3.8M    ./2023-09-22.md
2.8M    ./2023-10-05.md
2.4M    ./2023-10-06.md
2.3M    ./2023-10-03.md
2.2M    ./2023-09-25.md
1.0M    ./2023-09-28.md
392K    ./2023-10-31.md
348K    ./2024-01-16.md
```

So, perhaps, it was not crashing, just processing them and taking a long time. Seems like an Obsidian plugin went crazy those days and duplicated a lots of lines. After deduping the lines and getting back to normal size, everything seems to be working fine, thanks!!

**Comment by Feel-ix-343** [comment]
😳

The parser is fast but not *that* fast!

Haha great that you figured it out.

**Comment by Feel-ix-343** [comment]
Happy to find another with so many notes

**Comment by Feel-ix-343** [comment]
It appears that we can close this now.

**Comment by pwntester** [comment]
Thanks a lot!
