### ISSUE TITLE
cargo install no longer working

### ISSUE THREAD

**Issue by cfuehrmann** [Feel-ix-343/markdown-oxide#155]
I use markdown-oxide on WSL 1, inside which I run Ubuntu 24. 

My latest successful update via `cargo install` was about two weeks ago. Now I get this error:

```
cargo install --locked --git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide
    Updating git repository `https://github.com/Feel-ix-343/markdown-oxide.git`
error: failed to update submodule `docs/obsidian-minimal-publish` 
```

**Comment by Feel-ix-343** [comment]
Thanks for reporting!

This should be fixed now

**Comment by cfuehrmann** [comment]
Thanks ever so much - `cargo install` is working for me again.

**Comment by Feel-ix-343** [comment]
perfect!
