### ISSUE TITLE
Allow different and multiple markdown filetypes

### ISSUE THREAD

**Issue by ertwro** [Feel-ix-343/markdown-oxide#159]
Feature request:
Maybe the most annoying thing about most PKM systems is that they use markdown as their base filetype. There are many markdown filetypes like `{ ".org", ".qmd", "norg", ".rmd" ]` that have different features not available to regular markdown. So far I've only been able to use links and backlinks in telekasten.nvim form something like a markdown file to a quarto file, since something like obsidian only uses markdown.

**Comment by Feel-ix-343** [comment]
Hey! Thank you for the write up. 

I agree this would be useful, but I don't think this is in scope for the near future. I am primarily working on the plain markdown parser for now.
