### ISSUE TITLE
Ambiguous link to doc error using a Johnny Decimal folder scheme

### ISSUE THREAD

**Issue by kaesluder** [Feel-ix-343/markdown-oxide#160]
I get an "Ambiguous link to doc error" with the following link:

```md
- Investigation into [Ropey](https://docs.rs/ropey/latest/ropey/index.html) as a possible
  buffer backend for ed-debby. [[clone_ed_project]]
```

Referenced doc is located at `20 - 29 Computer Science/clone_ed_project.md`

![Screenshot_20240809_111315](https://github.com/user-attachments/assets/05b6a1fb-4eb5-4aa2-8895-af19613b933a)

**Comment by Feel-ix-343** [comment]
Hey!

Unfortunately I don't think this error is related to oxide. 

Do you have another markdown lsp running?

**Comment by kaesluder** [comment]
Thanks! It was marksman. Thanks for the suggestion.
