### ISSUE TITLE
Support tags defined on frontmatter

### ISSUE THREAD

**Issue by Scysta** [Feel-ix-343/markdown-oxide#161]
Hi. First of all, this project is great! I enjoy Neovim too much as to not use it for everything, including writing and note taking. 

I usually declare tags on the frontmatter of a file, and I write them without the `#` prefix. This is actually supported by Obsidian and obsidian.nvim, but I'm not getting tag completion with moxide. Here's what I mean:

![image](https://github.com/user-attachments/assets/55ea720e-5025-49f2-8598-69b09e7da9e1)

The suggestions are actually not meant to be tags (and probably they're fixed disabling tags on code blocks). Sure, I could manage to automate adding a `#` to every tag on every file, but I think they look cleaner without it, so I wanted to know if this is something that could be added!

**Comment by Feel-ix-343** [comment]
Hey! Thanks for the write up and kind words! I am happy you are enjoying the project.

We can consider adding this to version 0

**Comment by Feel-ix-343** [comment]
Hey again, this will be part of v1 through the new parser, and so that I can make v1 actually happen, I'm gonna put this off until v1 can tackle it.

**Comment by Feel-ix-343** [comment]
-- closing as this is not considered a current issue.

If I forget to do this in v1, surely this can be reopened.

**Comment by Dardanos-Aeolus** [comment]
As reference, once this is up for implementation:

This is already recognised in v0.24.0:
```
---
tags: rust
---
```

But this is not:
```
---
tags:
   - rust
   - python
---
```
But the second one would also be mandatory, because this is what Obsidian and obsidian.nvim both do.
