### ISSUE TITLE
Rename command adds "new_file_folder_path" to links

### ISSUE THREAD

**Issue by tadashi-aikawa** [Feel-ix-343/markdown-oxide#163]
Hi!

I'm very excited about using markdown-oxide for PKM in Neovim. Thank you as always for your great work! I have a question regarding the behavior of the rename command.

When I set the "new_file_folder_path" to `notes` and run the rename command to change `file1.md` to `file2.md`, `[[file1]]` gets updated to `[[notes/file2]]`. Is there a way to prevent the "new_file_folder_path" value from being added so that it only updates to `[[file2]]`?

### Reproduced steps

```
mkdir oxide-sandbox
cd oxide-sandbox
echo 'new_file_folder_path = "notes"' > .moxide.toml
mkdir notes
touch notes/file1.md
echo 'a [[file1]]' > index.md
vim notes/file1.md
```
↓
```
:lua vim.lsp.buf.rename()<CR>
file2<CR>
```

`Expected index.md`
```
a [[file2]]
```

`Actual index.md`
```
a [[notes/file2]]
```

---

Best regards.

**Comment by Feel-ix-343** [comment]
Hey!

This is surely a bug; 

Thank you for reporting.

**Comment by Feel-ix-343** [comment]
great write up!

**Comment by Feel-ix-343** [comment]
I am not working on v0 anymore, and this will be fixed in v1.

**Comment by Feel-ix-343** [comment]
I change my mind. fixing now!

**Comment by tadashi-aikawa** [comment]
Thank you! Sorry for my late response 🙏
