### ISSUE TITLE
Allow diacritics in tags

### ISSUE THREAD

**Issue by arcstur** [Feel-ix-343/markdown-oxide#164]
When I use a tag like #reflexões (reflections, in portuguese), it shows in the autocomplete as #reflex. Both (#reflex and #reflexões) are shown in the same go-to-definition. They seem to be equivalent, but that's not what I would want.

**Comment by Feel-ix-343** [comment]
Hey! 

This will be fixed in v1 with the treesitter parser.

**Comment by arcstur** [comment]
Thank you!!
