### ISSUE TITLE
List autocomplete

### ISSUE THREAD

**Issue by MattKang** [Feel-ix-343/markdown-oxide#165]
Hey It would be really fantastic if we could get autocomplete for lists, i.e. when I hit `Enter` at the end of a list, it would insert the `- ` or `1.` or `- [ ]` would autocomplete for the next entry.

Is this even technically possible with how autocomplete works in LSPs?

**Comment by Feel-ix-343** [comment]
Hey!

I think this would be an editor feature

For neovim, I use [bullets.nvim](https://github.com/bullets-vim/bullets.vim)

**Comment by Feel-ix-343** [comment]
Perhaps it could also be in a dedicated plugin

**Comment by MattKang** [comment]
Yes, that would certainly be a reasonable solution. Unfortunately using [helix](https://github.com/helix-editor/helix) whose plugin system is still in development. Out of curiosity, would this even be possible?

**Comment by Feel-ix-343** [comment]
Right

uhm 

maybe

but I suspect it would be a little janky

we could listen to file changes, detect if return was entered (after the fact, which is the issue) , then insert the bullet

This may work, however if things are slow, you would press enter, your cursor would go to the next line, and then (after a certain latency, which might be noticable), the bullet would be inserted

the issue is that we only get change information after the fact

**Comment by Feel-ix-343** [comment]
another idea is that we could expose an LSP command that would append a line with a bullet point and move the cursor (if possible). 

THe user could then map a key to this -- possibly return

**Comment by MattKang** [comment]
I think even a standard autocomplete option that would suggest "insert next item" when your cursor is in a list item would be useful. Apologies, I'm new to the world of LSPs and still learning what the API actually allows for.

**Comment by Feel-ix-343** [comment]
> I think even a standard autocomplete option that would suggest "insert next item" when your cursor is in a list item would be useful. Apologies, I'm new to the world of LSPs and still learning what the API actually allows for.

Definitealy fair, but this could be distracting

**Comment by Feel-ix-343** [comment]
> Apologies, I'm new to the world of LSPs and still learning what the API actually allows for.

No really to worry!

**Comment by MattKang** [comment]
If possible distracting, is it something that could be toggled through a config file?

**Comment by Feel-ix-343** [comment]
This would be possible!

What do you think about the command + mapping option?

**Comment by MattKang** [comment]
I'm thinking about it and wondering would this require me to exit insert mode in my editor?

**Comment by Feel-ix-343** [comment]
> Perhaps we could have this also map to just inserting a newline when not in a list such that one could just map to Enter

Yes that's what I was thinking.

And hopefully only enabled for markdown files

**Comment by MattKang** [comment]
Yes this would be great. What kind of lift would it take to get this feature released? If it helps, I'm happy to contribute, though I would first need to get up to speed with the project.

**Comment by joshpetit** [comment]
Hm this is interesting. I've never seen an LSP that offered autocomplete like this. Is there really no way to get this in the helix editor? This seems less like a feature and more so a workaround for the helix editor.

I feel for you though, I'm sure a lot of people have been looking forward to them releasing a plugin system.

**Comment by MattKang** [comment]
Agree that this is non-standard. but I do think that a "standard"-style list autocomplete would be reasonable for a markdown LSP.

**Comment by Feel-ix-343** [comment]
Hey. You could make a prototype using tower lsp and make a PR. 

For now I will close as I don't believe this is really missing or an issue. 

It would certainly be cool, however.
