### ISSUE TITLE
[Windows] Unresolved reference on links to files that are in folders

### ISSUE THREAD

**Issue by rutgersc** [Feel-ix-343/markdown-oxide#167]
See for example the following:

``` markdown
// nested/testlink.md
stuff
```

``` markdown
// linktester.md (windows) 
[[testlink]]: Unresolved Reference
[[nested\testlink]]: Works
[[nested/testlink]]: Unresolved Reference
```
``` markdown
// linktester.md (mac) 
[[testlink]]: Works
[[nested\testlink]]: Unresolved Reference
[[nested/testlink]]: Works
```

I would expect `[[testlink]]` to work on windows but it currently seems broken. Likely some issue with slashes?

**Comment by Feel-ix-343** [comment]
Yea it is likely due to rust path library.

This will be fixed in v1; We will chose `/`, not windows path.

**Comment by GitMurf** [comment]
I am on windows and all my [[wiki links]] are saying unresolved (using neovim). Unfortunately this makes this LSP unusable. Is there any update on this or plans to address? Or is windows basically not supported?
