### ISSUE TITLE
extension added at the end of references and headers instead of at the end of filename

### ISSUE THREAD

**Issue by ertwro** [Feel-ix-343/markdown-oxide#168]
Currently there are extensions added as an option for compatibility with wikilinks and other apps that use the extension at the end of the link,:
```lua
include_md_extension_md_link = true
include_md_extension_wikilink = true
```
This produces something like ```[Nicturia](Uro_definitions.md)``` which works ✅.

The problem is that when the reference to a header is autocompleted by cmp, it adds the extension at the end of the reference instead of at the end of  name of the file. This is the current behavior:
```md
[❌] [Nicturia](Uro_definitions#Nicturia.md)
```
Instead of like this, that would actually work:
```md
[✅] [Nicturia](Uro_definitions.md#Nicturia)
```

**Comment by Feel-ix-343** [comment]
Hmmmm yea that makes sense... thank you!!

This should be fixed in v1 when I get to it there. I am no longer developing v0. 

Thank you for reporting!

**Comment by flonle** [comment]
This was resolved in https://github.com/Feel-ix-343/markdown-oxide/pull/237.
