### ISSUE TITLE
feature request: autocomplete links by title

### ISSUE THREAD

**Issue by ibrokemypie** [Feel-ix-343/markdown-oxide#169]
I would like to be able to autocomplete links by title, not just by filename and header.

My notes system uses unique and meaningless filenames, leaving it up to the first H1 in the note to define the note's title. When I am writing a link in another note, I would like the autocomplete to search by this title, and exclude the filename entirely (from the search). 
When actually inserting the link, the title should be the link text, and the filename should be the link destination, eg. `(My Note File)[12345678.md]` for markdown links or `[[12345678.md|My Note File]]` for wikilinks.

As an additional extension, I expect other people with different setups would like to define their note titles differently, including from the filename or from frontmatter. This obviously is less important to me personally!

**Comment by Feel-ix-343** [comment]
Hey!

This is planned for v1!
