### ISSUE TITLE
Fix tag completions when tags are preceded by text

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#17]

**Comment by Feel-ix-343** [comment]
I think this is a nvim-cmp bug. Tags are working well in vscode. Here is a comparison:

![vscodenvimcmpcmp](https://github.com/Feel-ix-343/markdown-oxide/assets/88951499/01a0f034-0311-4b36-8170-e4f999435817)

**Comment by Feel-ix-343** [comment]
```[tasklist]
### My tasks
- [ ] Open a descriptive issue in nvim-cmp
```

**Comment by Feel-ix-343** [comment]
- [ ] Create a descriptive issue in nvim-cmp

**Comment by fnuttens** [comment]
FYI I can reproduce this in Helix, so it might not be a nvim-specific issue.
