### ISSUE TITLE
Editing links and titles automatically in Zed

### ISSUE THREAD

**Issue by Naadiyaar** [Feel-ix-343/markdown-oxide#171]
Changing a reference somewhere in a file or updating file names requires lots of search and edit without ability to update references, which is currently unavailable for the Zed editor (according to the wiki).
Opening this issue to express the demand for this feature.
Please make it available :)

**Comment by Feel-ix-343** [comment]
Hey!

I appreciate the enthusiasm. 

Unfortunately, as of last I checked, this was a zed issue with implementing the LSP.
