### ISSUE TITLE
Broken Pipe - Cargo Install on Alpine Linux with Helix

### ISSUE THREAD

**Issue by andar1an** [Feel-ix-343/markdown-oxide#173]
```
2024-09-09T13:02:27.448 helix_lsp::transport [ERROR] markdown-oxide err: <- StreamClosed
2024-09-09T13:02:27.448 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-09-09T13:02:27.448 helix_lsp::transport [ERROR] markdown-oxide err: <- IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2024-09-09T13:06:31.088 helix_lsp::transport [ERROR] markdown-oxide err: <- StreamClosed
```

I keep experiencing a repeating error whenever trying to use markdown-oxide with Helix on Alpine linux. 

Installed with `cargo install --locked --git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide`

Any suggestions to troubleshoot would be great.

**Comment by Feel-ix-343** [comment]
Hey! I am not working on v0 any more, but this will be fixed in v1.

Thank you for reporting

**Comment by Feel-ix-343** [comment]
Hey there is a good chance this is an issue with the helix LSP implementation and this is super tough to debug. 

Is the issue still happening? Also I am going to try to reproduce it by trying out the editor for my notes

**Comment by andar1an** [comment]
Hey @Feel-ix-343, 

Sorry, I am in process of setting up machines, I can't verify right now. 

I can let you know when I get back to this point, but I can't give you an eta of when that may be.

**Comment by Feel-ix-343** [comment]
No problem!

**Comment by andar1an** [comment]
I am at a point now where I can try debugging, let me know if there is something specific you want me to look for.

**Comment by Feel-ix-343** [comment]
Hey! I have been testing oxide with helix for a few weeks and no issues. Closing! Thanks for the report!
