### ISSUE TITLE
Rename doesn't work

### ISSUE THREAD

**Issue by Kyren223** [Feel-ix-343/markdown-oxide#176]
Renaming seems to only rename the links to the current file but doesn't rename the actual file on disk.

Also renaming is very unintuitive in my opinion as whatever is under the cursor gets suggested as the name
and it doesn't really make sense that the current file is the one being renamed.

A better renaming system:
When the cursor is on the file part of a link, ex: `[[My|File#someHeader]]` (| is cursor),
it should rename the file MyFile, including the actual file on disk and any other links referencing it.
When it's on the header such as `[[MyFile#som|eHeader]]` it should rename that file header, as if you were standing on the actual header and renaming it.

Bonus:
Add detection for external renaming (from oil.nvim, netrw etc), so when someone renames the file
it will also update the links.
Oil.nvim is supposed to already support notifying LSPs about rename/file moving/deletion etc
So it will most likely just involve adding support for that on the server.

Really good work! I just need renaming to work properly to cover my needs.

**Comment by Feel-ix-343** [comment]
Hey!

Yea I think this is the best approach.

I have stopped working on the current version of oxide, and am now focusing all of my developments on v1. I will add this to the list of planned fixes for v1.

**Comment by Kyren223** [comment]
Alright thanks! any estimate for when v1 will be released? even a rough one like if it's days/weeks/months/quarters/years etc

**Comment by Feel-ix-343** [comment]
hmmm well I just started a full-time job and I only work on this on the weekends...

perhaps 1-2.5 months (depending on how quickly the vector database comes along)

**Comment by Feel-ix-343** [comment]
Hey thank you so much! I am very excited to learn about that spec; not sure if it existed when I initially implemented rename? but its possible that I missed it (unfortunate).

**Comment by Feel-ix-343** [comment]
And oxide doesn't support renaming entities through their links.

**Comment by mgsloan** [comment]
Welcome!  Top level summary is:

* On `prepareRename`, server checks if the thing at the cursor position can be renamed, and sends the text range of the name that can be renamed.
* On `rename`, server responds with the modifications.
