### ISSUE TITLE
`--version` CLI flag

### ISSUE THREAD

**Issue by pcrockett** [Feel-ix-343/markdown-oxide#177]
I'd like to know what version of markdown-oxide I have running on my machine currently. It's not so easy to tell, as it takes no command line parameters and throwing a `--version` flag in there doesn't do anything.

**Comment by Feel-ix-343** [comment]
Hey! Thank you for contributing!

This is a good idea, although I don't think many people will use it. 

I'll happily accept a PR for this.

**Comment by Feel-ix-343** [comment]
Hey thanks for the suggestion! Will be pushed in the next version.
