### ISSUE TITLE
[Feature Request] Unlinked References Support

### ISSUE THREAD

**Issue by barcell1** [Feel-ix-343/markdown-oxide#185]
Usually PKMs have this feature, i dont found anything similar in neovim or builtin LSP

**Comment by Feel-ix-343** [comment]
Hey this is a great feature!

Currently the priority with this project is writing version 1, and I am happy to include this after the initial version of that is developed

**Comment by barcell1** [comment]
thanks bro, great plugin so far, i was able to move out from "standard pkms apps" to neovim just because of this plugin
