### ISSUE TITLE
Add dendron type syntax support for tags

### ISSUE THREAD

**Issue by gitsroid** [Feel-ix-343/markdown-oxide#187]
In dendron hierarchical structure is represented via "." [Tag syntax](https://wiki.dendron.so/notes/8bc9b3f1-8508-4d3a-a2de-be9f12ef1821/)

So the request would be to support `#tag.subtag.sub-tag`

**Comment by Feel-ix-343** [comment]
Hey thanks for reporting!

I'm afraid that since this is not a standard markdown feature, it does not make sense to support this. It would also complicate compatibility with Obsidian. 

Thank you
