### ISSUE TITLE
Add bibtex support

### ISSUE THREAD

**Issue by gitsroid** [Feel-ix-343/markdown-oxide#188]
In a PKM system it is essential the ability to reference to (external) resources.

A good way of doing this is using a BibTeX file "mybiblio.bib" so you can have centralized all your references (articles, books...). That also makes easy to cite your work using @citekey in the documents. This is great because then, via pandoc you can convert the document with those citekeys in other formats (like pdf) and have the citations an references in the output in your bibliographic style of choice.

What I am asking for is a tool similar to the obsidian plugin [Pandoc Reference List](https://github.com/mgmeyers/obsidian-pandoc-reference-list). When you put `@` in the document and start typing it starts showing the citekeys and titles corresponding to that citekey and then you select the one you want (it would be interesting to be able to select what variables of the bib file you want to choose when searching for it like citekey, author and publication so it only searches those ignoring the rest of the metadata). It does more than that (like rendering the full reference in the sidebar or showing the full reference in the CSL style you have chosen when putting the mouse in the citekey, which is also nice) but at least having this would be great.

**Comment by Feel-ix-343** [comment]
Hey thank you for the write-up! I would be very happy to accept a pull request for this (if it is a working one), but I am afraid this is too far in the backlog to prioritize right now. 

A new completion system, which is part of v1 will help with this significantly.

**Comment by MunsMan** [comment]
I'm interested in this feature as well, and I will try to prepare a pull request.

**Comment by Feel-ix-343** [comment]
ooh awesome.

**Comment by bdarcus** [comment]
This should work nicely for this use case:

https://github.com/kha-dinh/bibli-ls

**Comment by MunsMan** [comment]
Do you mean just as a second LSP? In my opinion, that would actually be a pretty clean solution. I will check it out.

I actually started implementing, but currently progress is stagnating due to exams…

**Comment by bdarcus** [comment]
> Do you mean just as a second LSP?

Yes.

> ... that would actually be a pretty clean solution. I will check it out.

Right.
