### ISSUE TITLE
GPL-3.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [Feel-ix-343/markdown-oxide#189]
👋 GPL-3.0 is deprecated by [SPDX](https://spdx.org/licenses/GPL-3.0), please consider using [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later). Thanks!

---

Need to update the license headers for the source files or just project readme to be more clear about the GPL license compatibility. 

---

relates to https://github.com/Homebrew/homebrew-core/pull/196143

**Comment by Feel-ix-343** [comment]
thanks for reporting! happy to fix this. I updated the licence to apache 2. Does this work?

**Comment by chenrui333** [comment]
yeah, totally works. I was kind of expecting you just declare the header and continue using GPL-3.0-or-later :)
