### ISSUE TITLE
Bug: regular links parsed as wiki linked 

### ISSUE THREAD

**Issue by Bekaboo** [Feel-ix-343/markdown-oxide#190]
Hi first of all thanks for all your works on markdown-oxide, it is super fast and easy to use.

I am switching from marksman to this markdown-oxide, however, I notice a difference between this language server and marksman about how they handle links:

![image](https://github.com/user-attachments/assets/09bc29df-eea2-48b6-a9e7-0ee06663253e)

Notice the "Unresolved references" diagnosics. I do not get these warnings when using marksman. They are all valid regular markdown links to local files and should not be warned. Seems that markdown-oxide is seeing them as invalid wiki links (correct me if I am wrong).

**Comment by TieWay59** [comment]
![image](https://github.com/user-attachments/assets/047d10d8-76cf-467d-a15e-eccad57588c7)

Hello, I've recently started using markdown-oxide and encountered the same issue. I've also noticed that the hover preview cards display the correct information, but I still receive warnings: 'Unresolved Reference used 28 times Obsidian LS'.

Thank you very much for your attention to this matter. I appreciate the work that has gone into developing markdown-oxide and understand it's a valuable tool for many users. I'm grateful for the opportunity to provide feedback and contribute to its improvement. Your efforts to maintain and enhance markdown-oxide are greatly appreciated by the community. @Feel-ix-343

**Comment by TieWay59** [comment]
PS @Bekaboo, I'd like to take this opportunity to ask you an unrelated question. Is markdown-oxide part of Visual Studio Code? If so, how can I configure it to display underlines as dashed lines?  （咋设置连接下划线为虚线的？ 好奇😆）

**Comment by Bekaboo** [comment]
@TieWay59 这不是 VSCode, 这是 Neovim, 相关配置在我的 [dot](https://github.com/bekaboo/dot.git) 仓库. 我们可以在那里讨论以避免过多离题内容.

**Comment by Feel-ix-343** [comment]
hey thanks for reporting! I can get to this this weekend

**Comment by Feel-ix-343** [comment]
Hey in v1 we will be switching to treesitter for parsing, so this should be fixed then. Thanks!
