### ISSUE TITLE
Linking to section headers in the same document

### ISSUE THREAD

**Issue by wardw** [Feel-ix-343/markdown-oxide#193]
I see there was some previous discussion to this in #60.  That seemed quite positive but the issue was later closed. 

Just curious is this is still on the roadmap?  Would personally love this.  And forgive me for the sell but it might also help adoption for folk like myself migrating from other tools where this seems quite well supported and so already have a bunch of links like this.

Great work regardless, awesome to have a solid markdown LSP!

**Comment by Feel-ix-343** [comment]
Hey thank you! I just implement the link resolution aspect of this. I simply expanded infile references to the full version. 

I also implemented infile completions for markdown style links, but not wiki links. 

I have been spending most of my time at my new job, and I have not been working on this project so much, but there are plans for a v1 for this, and these features will be more polished in that version.

**Comment by Feel-ix-343** [comment]
Hope that helps!

**Comment by wardw** [comment]
Thanks! I will take a look. 

And also good luck with the new job.

**Comment by Feel-ix-343** [comment]
thank you!
