### ISSUE TITLE
References fail in hidden directories

### ISSUE THREAD

**Issue by justinlovinger** [Feel-ix-343/markdown-oxide#194]
Something is odd about how hidden directories are handled. There are three related issues I can identify. One may be a design choice. One may be an oddity. The last is definitely unintended.

First, create `foo.md` and `.hidden/bar.md`. `[[bar]]` in `foo.md` fails. However, I can understand ignoring hidden directories being a design-choice.

Second, create `.hidden/foo.md` and `.hidden/bar.md`. `[[bar]]` in `.hidden/foo.md` fails and `[[foo]]` in `.hidden/bar.md` fails. I find this odd, because they are both in the same directory. However, I can understand this being a strange edge-case because the directory is hidden.

Here is where it gets stranger. Create `.hidden/foo.md` and `.hidden/bar.md`. Change directory to `.hidden`. `[[bar]]` in `foo.md` fails and `[[foo]]` in `bar.md` fails. So, because the working directory is hidden, files cannot reference each other.

**Comment by Feel-ix-343** [comment]
Hey! Thanks for reporting this and doing a bit of debugging on it!

1. Oxide completely ignores hidden directories (when parsing files, we filter out all directories that start with a ".") and 2. root dir resolution is complicated.

I would say that links in hidden folders are unsupported for now, and I don't think this is something oxide should support for the future.
