### ISSUE TITLE
Feature request: Notebook support

### ISSUE THREAD

**Issue by v217** [Feel-ix-343/markdown-oxide#196]
I use the `ms-vscode.vscode-markdown-notebook` **Markdown Notebook** extension by Microsoft.

The big advantage of the notebook interface is, that you have the combined advantages of the preview and the Markdown text editing experience. So you can view your formulas and graphics while editing the next paragraph. Or you can rearrange your cells easily. Since it's Markdown, version control works fine too.

**Comment by Feel-ix-343** [comment]
Hey! This plugin works through the LSP, so if the markdown notebooks support LSP, then oxide should work well. Otherwise, I'm happy to accept a PR for this :)

**Comment by v217** [comment]
Only the built-in LSP:  https://github.com/microsoft/vscode-markdown-languageservice

I guess there is no way to replace the built-in with another LSP?

(Up to now, I've only tried Jupyter-kernels, which work in the code sections.)

**Comment by Feel-ix-343** [comment]
perhaps this is a config option? markdown lsp: oxide -- or something like that
