### ISSUE TITLE
Support UI count for link references?

### ISSUE THREAD

**Issue by Oneechan69** [Feel-ix-343/markdown-oxide#197]
Markdown-oxide can show counts for tag references, reference counts for `[[` links would be very nice too, and be a good IDE equivalent of Obsidian's Strange New Worlds plugin.

**Comment by Feel-ix-343** [comment]
Hey thanks for the suggestion!

I think this would be cool! I'd be happy to take PRs for this and suggest to implement it using inlay hints.

**Comment by Feel-ix-343** [comment]
I'll leave this open for a couple weeks to see if anyone bites, but after that I'll need to close it to keep the repo focused on priorities.

**Comment by Oneechan69** [comment]
So I guess you're not gonna implement it.
