### ISSUE TITLE
Add blink-cmp support

### ISSUE THREAD

**Issue by Sir-Caljerque** [Feel-ix-343/markdown-oxide#199]
the shown config doesnt work for blink-cmp

**Comment by Feel-ix-343** [comment]
oh neat. I am not a huge can of nvim-cmp so this is exciting. I'm happy to accept a PR for this if you want to give it a shot!

**Comment by Sir-Caljerque** [comment]
it works outta the box 💀
also, i added these lines to blink config file:
```lua
local regex = "[-_]\\|\\k" -- Default regex

for _, client in ipairs(vim.lsp.get_clients()) do
	if client.name == "markdown-oxide" then
		regex = [[\(\k\| \|\/\|#\)\+]]
		break -- Exit the loop after finding the markdown-oxide LSP
	end
end

----------------------------------------------------------------------------------

completion = {
	keyword = {
		regex = regex,
	},
}

```

**Comment by Feel-ix-343** [comment]
yoo awesome

**Comment by Feel-ix-343** [comment]
is the regex even necessary now? I remember I made it because nvim-cmp was built very strangely. It was not necessary for other LSPs.

**Comment by Sir-Caljerque** [comment]
> is the regex even necessary now? I remember I made it because nvim-cmp was built very strangely. It was not necessary for other LSPs.

no, ive noticed 0 difference on it, i just included it bc its in the config. i highly doubt its necessary.

also, you have a typo in completion/mod.rs line 40
