### ISSUE TITLE
Is something like multiline bullet completion supported?

### ISSUE THREAD

**Issue by abadfr** [Feel-ix-343/markdown-oxide#200]
Hi! Not sure if this is the correct place to ask questions, it's not really an issue.

I'm just wondering if something like this is supported, or am i doing something wrong? I'm trying to integrate markdown-oxide to [codemirror](https://codemirror.net/), and got the completion working. However, search on bullet list items only works on content that is on the first line of the bullet. I'm not sure if I'm doing something wrong.

I also checked it in the VS Code extension, and the same thing happens. Seems like this isn't supported? Or maybe I need to configure something? 

![image](https://github.com/user-attachments/assets/7ff0483e-471a-4735-944c-bdc540481614)

Thanks!

**Comment by Feel-ix-343** [comment]
Hey!

This is not supported yet. I did a naive regex parsing bc it was fast and easy. 

With v1 I'm using treesitter and this will be solved!

**Comment by abadfr** [comment]
Gotcha. Looking forward to it!
