### ISSUE TITLE
Fix performance issues

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#29]
I have been noticing that completions and semantic tokens are quite slow on my vault.

**Comment by Feel-ix-343** [comment]
I'm going to try implementing completion_resolve so that not all of the completion information is sent at once

**Comment by Feel-ix-343** [comment]
Another interesting factor is that everything is quite fast when neovim is first opened, but the longer it runs, the slower interactions get.

**Comment by xorander00** [comment]
Glad I found this issue, as I was noticing the same thing.  I do have some larger files with tons of links. Can anything be done in terms of LSP server configuration or NeoVim configuration to throttle or debounce those messages? Possibly an option to disable link checking that would be enabled by default? I mainly use an explicit keymap to trigger completions and then I use that mainly to create new files.
