### ISSUE TITLE
Fix tag completions when tags are preceded by another tag

### ISSUE THREAD

**Issue by fnuttens** [Feel-ix-343/markdown-oxide#31]
At first I thought I was reproducing #17 in Helix, but in my case the completions don’t work only when there’s already a tag before on the same line:

```md
#existing-tag #Im-not-completed
```

**Comment by Feel-ix-343** [comment]
Hey! Thank you for reporting this.

I have an idea of why this is happening. I will get to it soon, then update here.

**Comment by Feel-ix-343** [comment]
And I am able to reproduce this in VS, fyu

**Comment by Feel-ix-343** [comment]
Solved! Tested it in VSCode and things are working as expected (still not working in nvim-cmp, unfortunately)

Of course repoen if its not working
