### ISSUE TITLE
Gives error in my (larger) Obsidian vault

### ISSUE THREAD

**Issue by tmke8** [Feel-ix-343/markdown-oxide#38]
I have two Obsidian vaults – one smaller, one larger. markdown-oxide works fine in the smaller one, but in the larger one, I get this error in nvim:

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1308: RPC[Error] code_name = InvalidParams, message = "Invalid params"
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1308: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I don't really understand what's the problem though.

What can I do to debug this? I built it with cargo from this commit: 2c577116 , I'm using NVIM v0.9.5 with these settings:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
lspconfig['markdown_oxide'].setup({
    capabilities = capabilities,
    on_attach = on_attach,
})
```
(`on_attach` is a pretty long function)

**Comment by tmke8** [comment]
Right after posting this, I noticed this in the README:

```
root_dir = lspconfig.util.root_pattern('.git', vim.fn.getcwd()), -- this is a temp fix for an error in the lspconfig for this LS
})
```

I have added this to the nvim config and did

```
touch .git
```
and now it works! Sorry!

**Comment by Feel-ix-343** [comment]
Yea sorry about that; trying to get the lspconfig fixed; there is an error with `single_file_support` I believe. #11 related

Also, if you have the vim.fn.getcwd() version it should work on any vault even without git.

**Comment by Feel-ix-343** [comment]
And also make sure to set capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true to get the language server to reload when you save files.

**Comment by tmke8** [comment]
It does indeed work without the `.git`. Specifically for Obsidian, I suppose I could also use `.obsidian` for the root pattern?

**Comment by Feel-ix-343** [comment]
sure yea great!
