### ISSUE TITLE
Failed to exclude fenced code for document symbol

### ISSUE THREAD

**Issue by ray-x** [Feel-ix-343/markdown-oxide#41]
For the following markdown `# python comment is not heading` should not appear in document symbols.

```markdown
# this is a heading

\```python
# python comment is not heading
print('hello world')
\```

```

**Comment by Feel-ix-343** [comment]
Ill work on this today

**Comment by Feel-ix-343** [comment]
This should be fixed in the latest commit

Also there are some new settings added related to this. You can set to resolve tags and links in code blocks. Check the readme for specifics. 

Thanks for reporting!
