### ISSUE TITLE
Add `cargo-binstal` support

### ISSUE THREAD

**Issue by KSaiAkshit** [Feel-ix-343/markdown-oxide#53]
I find [cargo-binstall](https://github.com/cargo-bins/cargo-binstall/) helpful when downloading cargo binaries, at least much faster than `wget` or `cargo install`. It would be great to integrate it into markdown-oxide. I could submit a PR if you are fine with it!

**Comment by Feel-ix-343** [comment]
Oooh nice! I'd love it if you opened a PR!
