### ISSUE TITLE
consistent follow link via <c-]>

### ISSUE THREAD

**Issue by anandkumar89** [Feel-ix-343/markdown-oxide#55]
I notice that currently <c-]> can follow the link to file under cursor. However this throws `No tags file` error when link is not resolved. 

**Proposed behaviour**: when link in unresolved, <c-]> creates the file and then opens it. 

personally I'd prefer `gf` command, that is more accessible.

**Comment by Feel-ix-343** [comment]
Hey! Thanks for reporting!

I don't think this is a markdown-oxide feature. 

The LS provides a code action for creating unresolved links, but no command to create and then go to definition.
