### ISSUE TITLE
Some bugs / feature requests 

### ISSUE THREAD

**Issue by anandkumar89** [Feel-ix-343/markdown-oxide#57]
- manual invokation of completion in certain cases (e.g. callouts) : Sometimes suggestion is not needed, one should be able to manually invoke suggestion (as in omnifunc) for lesser uses features that could be triggered more often. 
+ custom callouts 
- Calling `Telescope lsp_buf_references` directly jumps to file (likely has only one reference). I expected a telescope picker.
- show old name while renaming (already shown for some)

Plugin works flawlessly otherwise. Just for peace of mind, wanted to ask if texts, headings, filenames etc are being indexed somewhere for easy searching. 

Also, a heavier operation, block completion could be manually invoked after typing ^ (similar to obsidian's feature)

Apologies for mixing everything up. Feel free to pick ones actionable and close this issue.

**Comment by Feel-ix-343** [comment]
Another great comment!

1. Manual invocation: I would definitely want this to be in toggleable in settings. I think its possible to implement the manual invocation by dynamically modifying the completion character based on settings
2. Custom callouts could go in settings too!
3. Telescope: this is Telescope preference; vim.lsp.buf.reference (or whatever it's called) shows the list with just one item. There may be a config option on Telescope, and if not, definitely open an issue there!
4. Renaming: right now language servers do not control the name that shows up in the rename; there is nothing in the language server protocol that allows this. Instead, neovim just displays the word the cursor is in - which works for most cases in programming. This is however something an Obsidian.nvim + moxide integration could support - but I haven't gotten to this :( 
5. Telescope works great for a full text search; moxide also provides a workspace symbols for searching files, headings, tags, ... (I can't remember if anything else)
6. Block Completions: right now, you can type `[[ ` (note the space) or `[]( ` for fuzzy match block completions across the whole vault! Not sure if you knew this or are suggesting `[[^`/`[[file#^` as well?

Again I love to engage on this project; thank you for the comments!

**Comment by Feel-ix-343** [comment]
> Why I asked was - when I invoke renaming, I'm not sure what I'm renaming and what will happen after that. One approach could be to be more explicit by changing the prompt for each case - file, headings, tags, links e.g. when file is being renamed : "Enter new name file (updates all links across vault) : "

Totally understandable; I hope it isin't too difficult! One workaround is to hover before you rename; the hover preview will tell you what *referenceable* your cursor is over, which is what will be renamed. As for the prompt, I am not sure what this is honestly. Could you post a screenshot? Are you using an LSP plugin for renaming? In either case, unfortunately, I don't think the LSP can set the rename message. (I'll double check though)

I hope the completions are working well also

**Comment by Feel-ix-343** [comment]
I think this is sorted out?
