### ISSUE TITLE
Paragraph preview for lspsaga is not supported.

### ISSUE THREAD

**Issue by DeccanLin** [Feel-ix-343/markdown-oxide#59]
Paragraph preview for neovim lspsaga is not correct, only show heading, but whole paragraph is expected.

**Comment by Feel-ix-343** [comment]
Thanks for the comment!

Rigth now for heading previews, it shows the heading and X lines below it (5 I believe?)

For block previews, it only shows the line where the block index is placed

Both of these will be fix with a more advanced parser in the #48

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
