### ISSUE TITLE
The link to the heading in the current file is invalid.

### ISSUE THREAD

**Issue by DeccanLin** [Feel-ix-343/markdown-oxide#60]
Link to other heading inside same file doesn't work, like inside a.md, link [xxx](#test) doesn't work, it has to be [xxx])(a#test).

**Comment by Feel-ix-343** [comment]
Thank you for reporting!

Yes, I embarrassingly have not implemented this yet. I also just added it as a checkbox to the readme. 

Since it is now on the roadmap, I'll close this. 

Feel free to reopen and/or continue commenting here

**Comment by Feel-ix-343** [comment]
(no reason to close I realize)
