### ISSUE TITLE
emacs support?

### ISSUE THREAD

**Issue by Aneeqasif** [Feel-ix-343/markdown-oxide#61]
is it supported in emacs lsp?

**Comment by Aneeqasif** [comment]
> Not yet I don't believe, but great idea!
> 
> I'm really not to familiar with emacs and emacs lsp mode, so do you have any suggestions for building this support?

Yeah i can dive in but i am literally a couple of months in emacs and not that experienced with elisp.
If I do, beware you may get a little more notifications then normal :p

**Comment by Feel-ix-343** [comment]
That would be awesome hah

**Comment by Aneeqasif** [comment]
ok then i am not promising but ill try to squeeze some time for it and then get back to you with some progress.

**Comment by Feel-ix-343** [comment]
Awesome; looking forward to it. (I have always been scared of emacs lisp tbh)

**Comment by batmikun** [comment]
Hey! This wouldn't be to hard. Emacs has lsp built-in through the package Eglot. To be able to use markdown-oxide in Emacs, I need to know how is the command, how it executes in the cli.

For example for using pyright you do

```elips
  (add-to-list 'eglot-server-programs
               '(web-mode . ("typescript-language-server" "--stdio"))
               '(python-mode . ("pyright"))
               '(markdown-mode . ("cli-command"))))
```

**Comment by Feel-ix-343** [comment]
Hey thanks for the code snippet!

Once installed, markdown-oxide is available under the command `markdown-oxide`; that's it

**Comment by RyanGreenup** [comment]
> Hey! This wouldn't be to hard. Emacs has lsp built-in through the package Eglot. To be able to use markdown-oxide in Emacs, I need to know how is the command, how it executes in the cli.
> 
> For example for using pyright you do
> 
> ```
>   (add-to-list 'eglot-server-programs
>                '(web-mode . ("typescript-language-server" "--stdio"))
>                '(python-mode . ("pyright"))
>                '(markdown-mode . ("cli-command"))))
> ```

Yeah this is exactly right, so for me (on Doom Emacs) I was able to add this to `config.el`, open `~/Notes/slipbox/home.md` and then `M-x eglot` got it right. If `~/.cargo/bin` isn't in `$PATH` add the full path to `elisp`:


```elisp
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               `(markdown-mode . ,(eglot-alternatives
                                   '(("markdown-oxide"))))))
```

I'm not sure about `lsp-mode` though, `#TODO`.

This issue should be tagged as a documentation issue.

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
