### ISSUE TITLE
Obsidian.nvim Integration

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#65]
- [ ] Obsidian Nvim RFC

**Comment by Feel-ix-343** [comment]
Related 

- #21 
- #40

**Comment by Feel-ix-343** [comment]
With the focus on developing v1, this is not so much of a priority to me -- this and that the v0 APIs are not good enough to support any real integration. 

This can be a task for one v1 is developed; it will have better parsing and APIs that will really be helpful to obsidian.nvim.

**Comment by Feel-ix-343** [comment]
That being said, if Obsidian.nvim is still interested in integrating, we could start discussing the shape of the API. 

This could steer the direction of v1 development.

**Comment by joshpetit** [comment]
Related to this is being able to use aliases in wiki links. For example, if I have a file "Questions" that has the alias "Question", using `[[Question]]`` inside a file will cause markdown-oxide to add a diagnostic saying that the reference is not found. Obsidian.nvim however is able to find the reference.

**Comment by Feel-ix-343** [comment]
Hey! Thanks for the comment!

markdown-oxide actually does support aliases, but it is currently under the aliases property. 

Obsidian does not support a link in the form [[Question]], and if you see in the Obsidian editor, completions for Question will complete as [[file|Question]]. markdown-oxide does the same. 

Given it follows the behavior of Obsidian, I don't quite think this should change -- unless of course one is okay with their notes not working in Obsidian.

**Comment by joshpetit** [comment]
> Hey! Thanks for the comment!
> 
> markdown-oxide actually does support aliases, but it is currently under the aliases property. 
> 
> Obsidian does not support a link in the form [[Question]], and if you see in the Obsidian editor, completions for Question will complete as [[file|Question]]. markdown-oxide does the same. 
> 
> Given it follows the behavior of Obsidian, I don't quite think this should change -- unless of course one is okay with their notes not working in Obsidian. 

Phenomenal point thank you. I don't actually use obsidian, just the nvim plugin haha. I'm looking forward to seeing where markdown oxide goes!

**Comment by Feel-ix-343** [comment]
> I don't actually use obsidian, just the nvim plugin haha

Yep, and I don't even think you're the outlier!

An interesting ecosystem have here!

I appreciate the encouragement.

Hope to see you around.

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
