### ISSUE TITLE
Non markdown file completions (images)

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#68]

**Comment by Feel-ix-343** [comment]
This will probably build off of the v1 completions API, so it is a v1 thing

**Comment by Feel-ix-343** [comment]
on second thought, I am not really considering this now, so I will close. 

Please leave comments if you have any!

**Comment by cyruseuros** [comment]
This is actually rather important in my workflow. I use helix, where file completions are completely reliant on the LSP, and this means i cannot like to non-markdown files in my notes easily
