### ISSUE TITLE
extension or .visx not available for VSCodium

### ISSUE THREAD

**Issue by Rolograaf** [Feel-ix-343/markdown-oxide#72]
Cannot find extension "[Feel-ix-343/markdown-oxide](https://github.com/Feel-ix-343/markdown-oxide)" in VSCodium to install
tip: Grab the .visx and install it that way. 
Alas: "I have yet to set this up. Sorry!! By any chance could you open an issue for this? It would help me in prioritizing"

**Comment by Feel-ix-343** [comment]
Thank you!

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
