### ISSUE TITLE
NeoVim / Mason / Windows 11: The current platform is unsupported

### ISSUE THREAD

**Issue by Grueslayer** [Feel-ix-343/markdown-oxide#77]
Installing binary on Intel / Windows 11 / 64bit with

`:MasonInstall markdown-oxide`

fails with

```
  Failed
    ◍ markdown-oxide
      ▼ Displaying full log
        The current platform is unsupported.
```

this is because in the Mason registry (do you have access to it?) it is tagged with 

```json
    "source": {
      "id": "pkg:github/feel-ix-343/markdown-oxide@v0.0.21",
      "asset": [
        {
          "target": "win_x86",
          "file": "markdown-oxide-{{version}}-x86_64-pc-windows-gnu.zip",
          "bin": "markdown-oxide-{{version}}-x86_64-pc-windows-gnu/markdown-oxide.exe"
        }
      ]
    },
```

which means 32-bit but filename says `...-x86_64-...` and will be 64 bit. Target has to be changed to `win_x64` in the registry definition!

Meanwhile we can use

`:MasonInstall --target=win_x86 markdown-oxide`

**Comment by Feel-ix-343** [comment]
Hey! Thanks for reporting and giving a solution. I didn't know this about windows; my apologies. 

I don't have access to the mason repo, and unfortunately it will likely take weeks for a PR to get merged. I'll make it right now https://github.com/mason-org/mason-registry/pull/5570

**Comment by Feel-ix-343** [comment]
I expect this is related to #73

**Comment by Feel-ix-343** [comment]
This should be fixed now. Let me know how it works and I'll reopen if it doesn't
