### ISSUE TITLE
Installation using paru fails with "tried to update but --locked was passed"

### ISSUE THREAD

**Issue by yudjinn** [Feel-ix-343/markdown-oxide#79]
using `paru -S markdown-oxide-git` fails with the "tried to update but --locked was passed" error. I was able to resolve this locally by removing the `--locked` flag in the PKGBUILD 

Error:
``` 
error: the lock file <REDACTED>/.cache/yay/markdown-oxide-git/src/markdown-oxide/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

Note: I tried using the `--offline` flag but this does require network access, obviously.

**Comment by Feel-ix-343** [comment]
Hmmm I guess the pkgbuild was modified.

@sQVe what are your thoughts?

**Comment by Feel-ix-343** [comment]
Is this still not working?

**Comment by Feel-ix-343** [comment]
Let me know if this is still broken
