### ISSUE TITLE
Path completions (possibly configurable?)

### ISSUE THREAD

**Issue by dna113p** [Feel-ix-343/markdown-oxide#80]
I am not a regular Obsidian user so maybe my usage isn't the norm but I use a lot of index.md files inside of folders as a landing space for that area of my notes. Like `notes_root/projects/Work/index.md`. 

There are a couple of issues I've had dealing with paths (from notes_root):

typing `[[projects/` or `[](projects/)` I would want to get completions for files matching that path but none are given. If I type the full path manually the reference is resolved correctly and can be jumped to.

typing `[[index]]` which does give me completions, but it isn't clear which index file is which until viewing at the preview window for each completion. It would be nice in this case to get a path completion here since `index` does not resolve to a single note.
![image](https://github.com/Feel-ix-343/markdown-oxide/assets/2624171/6b4d0a93-fa5f-4ea7-bba4-5aca2680cc93)

**Comment by Feel-ix-343** [comment]
Hey!

Right now only filename completions are supported. I am planning to make this configurable. 

Thanks for the thorough write up!

**Comment by Feel-ix-343** [comment]
Also for the index case, you will get multiple completions, and when you try to get definitions, you will get multiple definitions.

Note that you _can_ write the path relative to root_dir too, and though you wont get completions, you will get one definition

**Comment by dna113p** [comment]
Great! I've found a good alternative, that might be better anyways - I have just given my index notes a more specific/unique top level header and can get completions to that.

Thanks for building this! Its so much nicer to use my normal editor than an entirely separate application for notes.

**Comment by Feel-ix-343** [comment]
I'm so happy to hear that!

I am definitely noting your interest in this feature too. You're not the only one

**Comment by Feel-ix-343** [comment]
This will build off of the v1 API structure, so it is a v1 feature now. 

This means the v1 foundation will be built first, then this (and other features in similar categories)

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
