### ISSUE TITLE
Gif -> mp4 for the feature previews

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#81]
https://www.reddit.com/r/logseq/comments/1cexbmq/comment/l1p0g1k/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Faster load times

- [ ] convert the gifs to mp4s
- [ ] works?

**Comment by ThatSealgair** [comment]
I am happy to implement this. Can I be assigned to this task?

**Comment by ThatSealgair** [comment]
So I looked into this. Unfortunately, what I gathered from [this thread](https://users.rust-lang.org/t/images-to-mp4-programmatically/60943/5) is that while technically possible, it may not be legal to implement. Another video format that could be used is `.webm` which would depend on client support to work.

**Comment by Feel-ix-343** [comment]
:fearful: 

I didn't know that. 

Any format will work; it just needs to be preview-able on the README

Thank you so much for helping!

**Comment by ThatSealgair** [comment]
I misread the issue. I thought it was an add-on to this LSP. I'll check to see if a `.webm` works, if not, I'll try to fix the existing gifs to reduce file-size and loading times.

**Comment by ThatSealgair** [comment]
I should be able to get MP4 videos to work for this project's README. I'll try to get it done by tomorrow night.

**Comment by Feel-ix-343** [comment]
Amazing! Thank you

**Comment by Feel-ix-343** [comment]
Hey let me know if you need any help with this!

**Comment by Locorock** [comment]
how about using something like https://github.com/marionebl/svg-term-cli to generate animated SVGs instead of videos?

**Comment by Feel-ix-343** [comment]
The website now handles this
