### ISSUE TITLE
Create an organized wiki for Markdown Oxide

### ISSUE THREAD

**Issue by Feel-ix-343** [Feel-ix-343/markdown-oxide#84]
https://github.com/Feel-ix-343/markdown-oxide/discussions/66

**Comment by RyanGreenup** [comment]
How about an [mdbook](https://github.com/rust-lang/mdBook) on [github pages](https://pages.github.com/)? We could throw it on the `pages` branch. I have an [example](https://ryangreenup.github.io/environmental-informatics-2023/) of one I used for lecturing last year in this [repo](https://github.com/RyanGreenup/environmental-informatics-2023).

- Pros
  - Static
  - Redistributable
  - Doesn't depend on pre-existing infrastructure
- Cons
  - External contributions will have to go through PR
    - Probably for the best tbh
  - No backlinks [^1]
  - No Wikilinks [^1]



[^1]: I have a Python script laying around that can be used as a plugin.

**Comment by RyanGreenup** [comment]
I've added an example of the `README.md` split up over an mdbook.

Given this projects close relationship with Obsidian, we may also want to consider [Quartz](https://github.com/jackyzha0/quartz). For reference there is also [mkdocs](https://www.mkdocs.org/).

You can have at the example [here](https://github.com/RyanGreenup/markdown-oxide/tree/main/mdbook):

```sh
# Clone Repo
repo=markdown-oxide
branch=mdbook
cd $(mktemp -d)
git clone https://github.com/RyanGreenup/${repo}

# Checkout Branch
cd ${repo}
git checkout ${branch}
git pull origin ${branch}
git checkout ${branch}

# Serve the book
./mdbook/run.py
```

This is a bit of a specific setup for mdbook that may need to be adapted. I use this template as a static site for my notes (although I've sinced moved into wikijs).

- Backlinks
    - A python script builds the backlinks and adds to each page
        - This script first does =os.chdir(os.path.dirname(__file__))=
- Wikilinks
    - These will be converted to markdown links during rendering
        - =BUG=: Including within code blocks =#TODO=
- Summary.md
    - I build this before running so unlisted pages are always shown
        - This works better for my vault because I don't want to list them all
        - If memory serves me right, these are ordered by pagerank

**Comment by Feel-ix-343** [comment]
Ooh great yea. 

Mdbook fits the rust ethos too.

Looks great.

I do also want to make a sexy homepage, which can of course link to the docs

**Comment by Feel-ix-343** [comment]
What about just using the github wiki? What are the downsides to this?

**Comment by RyanGreenup** [comment]
> What about just using the github wiki? What are the downsides to this?

- Search
    -  mdbook and quartz have better search
        - this isn't a big deal if the wiki has lots of links and a good structure. 
- redistributable
    - a static site can be downloaded and viewed locally

I think, overall just using GitHub wiki is probably the best thing to do here. From there we could use mdbook or quartz and deploy it on GitHub pages at any time in the future and it could simply compliment the wiki.

**Comment by Feel-ix-343** [comment]
Great points and I agree. 

Also it seems that the wiki can be downloaded locally too: 
![image](https://github.com/Feel-ix-343/markdown-oxide/assets/88951499/877f4601-b8ae-4624-b17f-2cac404f6c03)

**Comment by EphemeralDev** [comment]
I think it should be simplified by having a feature comparison table/chart upfront and moving the more thorough explanations/visual aids to the wiki or github pages. For instance, I currently use marksman, but i would like to see how it compares to markdown oxide, logseq, and obsidian. I feel like it should be organized as follows: 

1. What markdown oxide is/does
2. How it compares to similar tools
2.1. Brief explanation of best/most used features
2.2. Feature comparison table (in my opinion probably between marksman, logseq, obsidian)
3. Installation instructions
4. Link to docs that contain more thorough explanations on configuration options and features.

**Comment by Feel-ix-343** [comment]
I really like that. Thank you

**Comment by Feel-ix-343** [comment]
I am currently working on docs through obsidian publish!

Check here for the current status https://publish.obsidian.md/markdown-oxide/Home

I am pretty excited about this!

All of it is being written with Markdown Oxide and Obsidian
