### ISSUE TITLE
Problems with cwd root-dir detection

### ISSUE THREAD

**Issue by clobrano** [Feel-ix-343/markdown-oxide#88]
I assume this might be some error in my configuration, but I see that any file that isn't already opened returns an "Unresolved reference" error. Even if the count of the references is working fine.

I created a test vault with this structure
```
tree
.
├── journal
│   ├── 2024-05-16.md
│   └── 2024-05-17.md
├── resources
│   └── some-data.md
└── tasks
    └── projectA.md
```

The current directory is the root of the vault (so above `journal`, `resources` and `tasks`) and only `some-data` is correctly referenced.

![image](https://github.com/Feel-ix-343/markdown-oxide/assets/2883614/15bd7030-ecf3-4242-be18-9961e531b907)

It seems to work better for files under the same folder though. I moved into `journal` and restarted the server and this made `2024-05-16` file correctly referenced.

**Comment by Feel-ix-343** [comment]
Hey! 

Could you share the result of lspinfo?

I think there is an issue with root_dir possibly

**Comment by clobrano** [comment]
You might be right. That `running in single file mode` is suspect :) 

```
Client: markdown_oxide (id: 3, bufnr: [5, 53])                                                                                                                                                                     
~                        filetypes:       markdown                                                                                                                                                                                         
~                        autostart:       true                                                                                                                                                                                             
~                        root directory:  Running in single file mode.                                                                                                                                                                     
~                        cmd:             /home/clobrano/.local/share/nvim/mason/bin/markdown-oxide 
```

**Comment by Feel-ix-343** [comment]
Definitely.

In single file mode, root directory is the directory of the first opened file.

However, single file mode is unexpected on neovim; could you post your lspconfig for this?

**Comment by Feel-ix-343** [comment]
That is one way; there is also .git, .moxide.toml and if not those, the cwd of neovim

**Comment by clobrano** [comment]
It seems that the `cwd` option is not working well (at least in this configuration). I do use it with code, so it works with `.git` and as soon as I added `.obsidian` it worked in the test vault too.

my lsp config is a bit scattered through my files, not sure this is all

```
{ -- LSP Configuration & Plugins
    'neovim/nvim-lspconfig',
    dependencies = {
      -- Automatically install LSPs to stdpath for neovim
      { 'williamboman/mason.nvim', config = true },
      'williamboman/mason-lspconfig.nvim',

`require('fidget').setup({})`
      { 'j-hui/fidget.nvim',       tag = 'legacy', opts = {} },

      'folke/neodev.nvim',
    },
  },
```

**Comment by Feel-ix-343** [comment]
Ok thanks Ill investigate

**Comment by Feel-ix-343** [comment]
Awesome!

**Comment by Feel-ix-343** [comment]
Hey sorry for the delay -- was on vacation. 

I think I will look more into this when I am making the #95

**Comment by Feel-ix-343** [comment]
in v1 I will be rewriting all of this code, so I will fix this then.
