### ISSUE TITLE
Auto-continue ordered and unordered lists

### ISSUE THREAD

**Issue by jeromg** [Feel-ix-343/markdown-oxide#89]
Hi there,

I'm just starting to use neovim to edit markdown and I just discovered moxide. I'm really impressed by what it can do out of the box (and the clever use of LSP).

The feature that I'm missing at the moment to edit my markdown files is the ability to auto-continue ordered and unordered lists.
How do you guys do for this kind of things? Other neovim plugins? Specific settings?

Thanks and congrats to @Feel-ix-343 for this great tool.

Cheers,

Jerome

**Comment by Feel-ix-343** [comment]
Hey! Thank you so much for the kind words!

I don't think markdown-oxide should provide this as it is a part of the text-editing experience that you bring.

For neovim, I use [this plugin](https://github.com/bullets-vim/bullets.vim). 

Let me know if there is anything else!
