### ISSUE TITLE
Add git install to readme

### ISSUE THREAD

**Issue by melMass** [Feel-ix-343/markdown-oxide#9]
Thanks for this project.
Most people might know but I would add the following option to the readme:

## install from git
`cargo install --git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide`

**Comment by Feel-ix-343** [comment]
I may just list the project on cargo, allowing for `cargo install markdown-oxide`. This would be better, right?

**Comment by melMass** [comment]
Indeed this will not be useful once published unless people want to use "main", I personally install a lot of binaries this way to rely more on the git tree than the tagged releases

**Comment by Feel-ix-343** [comment]
That makes sense. I updated the readme. Closing this issue now.
